# Generated by Django 5.0.4 on 2024-05-06 11:04

import uploadsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="file",
            field=models.FileField(upload_to=uploadsapp.models.user_directory_path),
        ),
    ]
