# Generated by Django 5.0.4 on 2024-05-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadsapp", "0002_alter_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
